spring.application.name=gestion-guias-despacho
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/guias-despacho-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_AD_B2C_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_AD_B2C_JWK_SET_URI}

management.endpoints.web.exposure.include=health,info

app.aws.region=${AWS_REGION:us-east-1}
app.aws.s3.bucket=${S3_BUCKET:guias-despacho}
